version: '3.10'
services:
  web:
    build: .
    environment:
      - DEVELOPMENT_DATABASE_URI=postgresql://digfutsys:digfutsys@db/digfutsys
    depends_on:
      - db
    ports:
      - 5000:5000
    container_name: digfutsys_web

  db:
    container_name: digfutsys_db
    image: postgres:13.4-alpine
    volumes:
      - postgres_data:/var/lib/pstgrsql/data/
    environment:
      - POSTGRES_USER=digfutsys
      - POSTGRES_PASSWORD=digfutsys
      - POSTGRES_DB=digfutsys

volumes:
  postgres_data: